version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
      - /data/tweets_corona:/data/tweets_corona:ro
    ports:
      - 1097:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    build: ./services/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=twitter
      - POSTGRES_PASSWORD=twitter
      - POSTGRES_DB=twitter_dev

volumes:
  postgres_data:
